[workspace]
members = [
  "pluma_analyzer",
  "pluma_ast",
  "pluma_cli",
  "pluma_compiler",
  "pluma_constants",
  "pluma_diagnostics",
  "pluma_emitter",
  "pluma_module",
  "pluma_parser",
  "pluma_repl",
  "pluma_visitor",
]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
