[workspace]
members = [
  "analyzer",
  "ast",
  "cli",
  "compiler",
  "constants",
  "diagnostics",
  "macros",
  "module",
  "parser",
  "tests",
  "visitor",
]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
