#!/bin/bash

# This is a simple task runner. All tasks are defined in this file.
# usage: ./task some_name (runs function called `task_some_name`)

task_check() {
	cargo check
}

task_build() {
	cargo build --bin cli
}

task_build_release() {
	cargo build --release --bin cli
}

task_example() {
	local example=${1:-examples/simple-math.pa}

	cargo run --quiet --bin cli check "$example"
}

"task_$1" ${@:2}