// One #[test] per execution fixture. Compiles each fixture to a WasmGC artifact
// and runs it under V8 — the same engine `pluma run` ships — capturing stdout +
// stderr through the host's buffered io sink. Snapshot lives in `run.snap` next to
// the fixture. Two roots, same harness: `run/` is the happy-path corpus (status
// `ok`) and `run-fail/` holds programs that compile but fail at runtime (status
// `runtime error`). Compile-error cases live in `tests/analyze/` (the frontend
// suite), not here.
//
// This is the wasm backend's standing regression guard: with the VM oracle gone,
// the snapshots are generated by — and pin — the deploy backend directly.

use compiler::{Compiler, Diagnostic};
use std::path::Path;

datatest_stable::harness! {
	{ test = run_fixture, root = concat!(env!("CARGO_MANIFEST_DIR"), "/run"), pattern = r"main\.pa$" },
	{ test = run_fixture, root = concat!(env!("CARGO_MANIFEST_DIR"), "/run-fail"), pattern = r"main\.pa$" },
}

fn run_fixture(path: &Path) -> datatest_stable::Result<()> {
	let fixture_dir = path.parent().unwrap();
	// See the analogous comment in analyze.rs: anchor cwd at the workspace
	// root (one level up from this crate) so portable relative paths show
	// up in fixture output.
	let workspace = Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap();
	let _ = std::env::set_current_dir(workspace);
	let relative = path.strip_prefix(workspace).unwrap_or(path);

	// If a fixture has stdin.txt next to main.pa, feed its bytes as the
	// program's stdin. Otherwise stdin is empty (any read returns EOF).
	let stdin_bytes = std::fs::read(fixture_dir.join("stdin.txt")).unwrap_or_default();

	let result = (|| -> Result<host::RunCapture, RunError> {
		// Ungated, exactly like `pluma run`: the fixtures compile to wasm and run
		// under V8 with full host capabilities, so no deploy target is selected.
		let mut compiler = Compiler::from_entry_path(relative.to_str().unwrap().to_string())
			.map_err(RunError::Diagnostics)?;
		compiler.check().map_err(RunError::Diagnostics)?;
		// Raw lowered IR — the wasm backend runs its own internal pipeline,
		// exactly as `pluma run` / `pluma build` drive it.
		let ir_program = ir::lower(&compiler).map_err(RunError::Lower)?;
		let bytes = wasm::emit(&ir_program).map_err(RunError::WasmEmit)?;
		Ok(host::run_wasm_v8_captured(&bytes, &stdin_bytes))
	})();

	// Reassemble the status / stdout / stderr snapshot block. The V8 runner folds a
	// runtime failure's message into `status` (`"runtime error: <msg>"`); the
	// snapshot keeps the bare `runtime error` status and appends the message to
	// stderr (after any stderr the program itself produced), matching the shape the
	// suite has always pinned.
	let (status, stdout, stderr) = match result {
		Ok(cap) => {
			if let Some(msg) = cap.status.strip_prefix("runtime error: ") {
				let mut stderr = cap.stderr;
				stderr.push_str(msg);
				stderr.push('\n');
				("runtime error".to_string(), cap.stdout, stderr)
			} else {
				// "ok" (any other status would be a host/module-level error, which
				// we surface verbatim so it can't masquerade as a clean run).
				(cap.status, cap.stdout, cap.stderr)
			}
		}
		Err(RunError::Diagnostics(d)) => (
			"compile error".to_string(),
			String::new(),
			format_diagnostics(&d),
		),
		Err(RunError::Lower(msg)) => (
			"compile error".to_string(),
			String::new(),
			format!("{}\n", msg),
		),
		Err(RunError::WasmEmit(diags)) => (
			"wasm codegen error".to_string(),
			String::new(),
			format!("{}\n", diags.0.join("; ")),
		),
	};

	let combined = format!(
		"== status ==\n{}\n== stdout ==\n{}== stderr ==\n{}",
		status, stdout, stderr
	);

	insta::with_settings!({
		snapshot_path => fixture_dir,
		prepend_module_to_snapshot => false,
	}, {
		insta::assert_snapshot!("run", combined);
	});

	Ok(())
}

enum RunError {
	Diagnostics(Vec<Diagnostic>),
	Lower(String),
	WasmEmit(wasm::Diagnostics),
}

fn format_diagnostics(diagnostics: &[Diagnostic]) -> String {
	use std::fmt::Write;
	let mut out = String::new();
	for d in diagnostics {
		let kind = if d.is_error() { "error" } else { "warning" };
		writeln!(&mut out, "{}: {}", kind, d.message).unwrap();
	}
	out
}
