// Builtin tags. The VM owns the implementations (in eval.rs); codegen
// emits CallBuiltin instructions referring to these by tag.

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum Builtin {
	Print,
	ToString,
	Matches,
	// Numeric trait method bodies. Hidden — users always go through the
	// trait method (`numeric.add` etc.). Live inside per-instance
	// `Value::Dict`s built by codegen at program load.
	IntAdd,
	IntSub,
	IntMul,
	IntDiv,
	IntNegate,
	FloatAdd,
	FloatSub,
	FloatMul,
	FloatDiv,
	FloatNegate,
	// `ord` trait method bodies. Each returns one of the
	// `__prelude__.ordering` variants (`lt`, `eq`, `gt`).
	IntCompare,
	FloatCompare,
	StringCompare,
	// `hash` trait method bodies. Each returns an int. The actual hash
	// algorithm is intentionally simple — these aren't cryptographic, just
	// good enough for hash-map bucketing. Future cleanups may switch to a
	// faster non-stdlib hasher.
	IntHash,
	FloatHash,
	StringHash,
	BoolHash,
	ListLength,
	ListIsEmpty,
	ListReverse,
	ListConcat,
	ListContains,
	ListMap,
	ListFilter,
	ListFold,
	ListEach,
	ListHead,
	ListTail,
	ListTake,
	ListDrop,
	ListFind,
	ListAny,
	ListAll,
	ListSort,
	MathToFloat,
	MathToInt,
	MathSqrt,
	MathAbs,
	MathFloor,
	MathCeil,
	MathRound,
	MathLog,
	MathLog10,
	MathLog2,
	MathExp,
	MathSin,
	MathCos,
	MathTan,
	StringLength,
	StringIsEmpty,
	StringToUpper,
	StringToLower,
	StringTrim,
	StringContains,
	StringStartsWith,
	StringEndsWith,
	StringJoin,
	StringSplit,
	StringReplace,
	StringToInt,
	StringToFloat,
	IoPrint,
	IoPrintErr,
	IoWrite,
	IoWriteErr,
	IoRead,
	IoReadAll,
	IoReadFile,
	IoWriteFile,
	IoAppendFile,
	IoFileExists,
	IoDeleteFile,
	IoArgs,
	IoEnv,
	IoExit,
}
