// Builtin tags. The VM owns the implementations (in eval.rs); codegen
// emits CallBuiltin instructions referring to these by tag.

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum Builtin {
	Print,
	ToString,
	Matches,
	// Numeric trait method bodies. Hidden — users always go through the
	// trait method (`numeric.add` etc.). Live inside per-instance
	// `Value::Dict`s built by codegen at program load.
	IntAdd,
	IntSub,
	IntMul,
	IntDiv,
	IntNegate,
	FloatAdd,
	FloatSub,
	FloatMul,
	FloatDiv,
	FloatNegate,
	// `ord` trait method bodies. Each returns one of the
	// `__prelude__.ordering` variants (`lt`, `eq`, `gt`).
	IntCompare,
	FloatCompare,
	StringCompare,
	// `hash` trait method bodies. Each returns an int. The actual hash
	// algorithm is intentionally simple — these aren't cryptographic, just
	// good enough for hash-map bucketing. Future cleanups may switch to a
	// faster non-stdlib hasher.
	IntHash,
	FloatHash,
	StringHash,
	BoolHash,
	ListLength,
	ListIsEmpty,
	ListReverse,
	ListConcat,
	ListContains,
	ListMap,
	ListFilter,
	ListFold,
	ListEach,
	ListHead,
	ListTail,
	ListTake,
	ListDrop,
	ListFind,
	ListAny,
	ListAll,
	ListSort,
	MathToFloat,
	MathToInt,
	MathSqrt,
	MathAbs,
	MathFloor,
	MathCeil,
	MathRound,
	MathLog,
	MathLog10,
	MathLog2,
	MathExp,
	MathSin,
	MathCos,
	MathTan,
	StringLength,
	StringIsEmpty,
	StringToUpper,
	StringToLower,
	StringTrim,
	StringContains,
	StringStartsWith,
	StringEndsWith,
	StringJoin,
	StringSplit,
	StringReplace,
	StringToInt,
	StringToFloat,
	StringToBytes,
	BytesLength,
	BytesIsEmpty,
	BytesAt,
	BytesConcat,
	BytesSlice,
	BytesContains,
	BytesStartsWith,
	BytesEndsWith,
	BytesRepeat,
	BytesReverse,
	BytesToList,
	BytesFromList,
	BytesJoin,
	BytesSplit,
	BytesToString,
	BytesCompare,
	BytesHash,
	IoPrint,
	IoPrintErr,
	IoWrite,
	IoWriteErr,
	IoRead,
	IoReadAll,
	IoReadFile,
	IoWriteFile,
	IoAppendFile,
	IoFileExists,
	IoDeleteFile,
	IoArgs,
	IoEnv,
	IoExit,
	IoReadAllBytes,
	IoReadFileBytes,
	IoWriteFileBytes,
	IoAppendFileBytes,
	IoWriteBytes,
	IoWriteErrBytes,
	// Map builtins. Those constrained by `where (hash k)` receive the
	// hash dict as their first arg; the implementation pulls slot 0 of
	// the dict and invokes it on the key to compute its hash.
	MapEmpty,
	MapInsert,
	MapLookup,
	MapRemove,
	MapContainsKey,
	MapSize,
	MapKeys,
	MapValues,
	MapEntries,
	MapFromEntries,
	MapMerge,
	MapMap,
	MapFilter,
	MapFold,
	// Mutable-cell builtins (`core.ref`). `new` allocates a fresh
	// `Rc<RefCell<Value>>`; `get`/`set`/`update` operate on the cell in
	// place. Identity is preserved across reads — calling `get` on the
	// same ref twice returns the same cell-backed value.
	RefNew,
	RefGet,
	RefSet,
	RefUpdate,
	// `then`-chaining builtins for the prelude's option/result enums.
	// `option.then` invokes the continuation on `some`'s payload and
	// passes `none` through; `result.then` does the same for `ok` and
	// passes `err` through. The `try` syntax form desugars to these.
	OptionThen,
	ResultThen,
}
