[package]
name = "pluma"
version = "0.1.0"
license = "MIT"
authors = ["Reid Mitchell <reidmitchell1@gmail.com>"]
edition = "2018"

[dependencies]
atty = "0.2.13"
glob = "0.3.0"
compiler = { path = "../compiler" }
constants = { path = "../constants" }
diagnostics = { path = "../diagnostics" }
parser = { path = "../parser" }
repl = { path = "../repl" }