[package]
name = "parser"
version = "0.1.0"
authors = ["Reid Mitchell <reidmitchell1@gmail.com>"]
edition = "2018"

[dependencies]
ast = { path = "../ast" }
macros = { path = "../macros" }

[dev-dependencies]
insta = "1.13.0"