mod call;
mod definition;
mod expr;
mod identifier;
mod r#if;
mod lambda;
mod r#let;
mod literal;
mod module;
mod operator;
mod pattern;
mod regex;
mod type_expr;
mod type_identifier;
mod when;
mod r#while;

pub use self::call::*;
pub use self::definition::*;
pub use self::expr::*;
pub use self::identifier::*;
pub use self::lambda::*;
pub use self::literal::*;
pub use self::module::*;
pub use self::operator::*;
pub use self::pattern::*;
pub use self::r#if::*;
pub use self::r#let::*;
pub use self::r#while::*;
pub use self::regex::*;
pub use self::type_expr::*;
pub use self::type_identifier::*;
pub use self::when::*;

pub type Span = (usize, usize);
