// The `pluma build --web` bundle: the WasmGC artifact plus the JS glue
// that runs it in a real browser. `app.wasm` is the compiled module (emitted under
// the `Web` target, so `std/web/dom` lowers to host imports); `loader.js` supplies
// those imports backed by the real DOM and drives the module; `index.html` is a
// minimal shell that loads the loader.
//
// The loader mirrors the sys host's import-object shape (`host/src/v8host.rs`):
// a `{ pluma: { ... } }` object over the module's exported `"memory"`, with each
// `dom-*` import backed by the live `document`. The whole DOM surface is provided
// regardless of which subset a given module imports (extras are ignored), exactly
// as the Rust host registers its full set.

use std::path::Path;

/// Write the three-file browser bundle into `dir`: `app.wasm`, `loader.js`,
/// `index.html`. `dir` is created if missing.
pub(crate) fn write_bundle(dir: &Path, wasm: &[u8]) -> std::io::Result<()> {
	std::fs::create_dir_all(dir)?;
	std::fs::write(dir.join("app.wasm"), wasm)?;
	std::fs::write(dir.join("loader.js"), LOADER_JS)?;
	std::fs::write(dir.join("index.html"), INDEX_HTML)?;
	Ok(())
}

const INDEX_HTML: &str = "<!doctype html>\n\
<html>\n\
<head><meta charset=\"utf-8\"><title>Pluma app</title></head>\n\
<body>\n\
<script type=\"module\" src=\"loader.js\"></script>\n\
</body>\n\
</html>\n";

pub(crate) const LOADER_JS: &str = r#"// Pluma browser loader — instantiates app.wasm and serves its `pluma.*` host
// imports from the real DOM. Generated by `pluma build --web`.

const dec = new TextDecoder();
const enc = new TextEncoder();
let memory;   // the module's exported WebAssembly.Memory
let exports;  // the instance's exports (for the event-dispatch callback)
let lastError = "";              // errno-style channel for io-last-error
let readStash = new Uint8Array(0); // overflow buffer drained by io-copyout
const rpcStreams = new Map();     // token -> AbortController for live RPC subscriptions

// Re-read the backing buffer on every access — a memory.grow swaps it out.
const u8 = () => new Uint8Array(memory.buffer);
const readStr = (ptr, len) => dec.decode(u8().subarray(ptr, ptr + len));
// Write `s`'s UTF-8 into scratch at `dst` (≤ cap bytes) and return its true length.
const writeStr = (dst, cap, s) => {
  const b = enc.encode(s);
  const n = Math.min(b.length, cap < 0 ? 0 : cap);
  u8().set(b.subarray(0, n), dst);
  return b.length;
};
const hexEncode = (b) => {
  let s = "";
  for (let i = 0; i < b.length; i++) s += (b[i] & 0xff).toString(16).padStart(2, "0");
  return s;
};
const hexDecode = (s) => {
  const b = new Uint8Array(s.length >> 1);
  for (let i = 0; i < b.length; i++) b[i] = parseInt(s.substr(i * 2, 2), 16);
  return b;
};
// Hand one event to a wasm channel: reserve scratch, copy the payload in, signal the
// kind (next=0, done=1, fault=2). Shared by the streaming subscription reader and the
// unary single-shot fetch. Each call re-readies a parked puller and pumps the scheduler.
const pushStreamEvent = (token, kind, bytes) => {
  const n = bytes ? bytes.length : 0;
  const dst = exports.__rpc_stream_alloc(token, n);
  if (n) u8().set(bytes, dst);
  exports.__rpc_stream_event(token, kind, dst, n);
};

// `__tostring` delegates float formatting here: integers render as `N.0`, the
// rest via the JS default (matches the Rust host's cb_float_to_str).
const floatToStr = (n, ptr, cap) => {
  const s = Number.isFinite(n) && Number.isInteger(n) ? n.toFixed(1) : String(n);
  return writeStr(ptr, cap, s);
};

const pluma = {
  float_to_str: floatToStr,
  // std/web/dom — node handles are opaque JS DOM nodes flowing through wasm $extern boxes.
  "dom-body": () => document.body,
  "dom-create-element": (p, l) => document.createElement(readStr(p, l)),
  "dom-create-text": (p, l) => document.createTextNode(readStr(p, l)),
  "dom-append-child": (parent, child) => { parent.appendChild(child); },
  "dom-insert-before": (parent, node, before) => { parent.insertBefore(node, before); },
  "dom-remove-child": (parent, child) => { parent.removeChild(child); },
  // Index a node's children — `render.hydrate` walks the server-rendered tree by
  // position (the view tree and the SSR'd DOM are 1:1 in document order).
  "dom-child-at": (n, i) => n.childNodes[i],
  "dom-replace-child": (parent, node, old) => { parent.replaceChild(node, old); },
  "dom-set-attribute": (n, np, nl, vp, vl) => n.setAttribute(readStr(np, nl), readStr(vp, vl)),
  "dom-remove-attribute": (n, p, l) => n.removeAttribute(readStr(p, l)),
  // DOM *property* writes (`node[name] = value`), distinct from attributes: a string
  // property (e.g. `value`) and a bool property (e.g. `checked`/`disabled`). The bool
  // rides as an i32 so `!!flag` is a real boolean (`node.disabled = "false"` is truthy).
  "dom-set-string-property": (n, np, nl, vp, vl) => { n[readStr(np, nl)] = readStr(vp, vl); },
  "dom-set-bool-property": (n, np, nl, v) => { n[readStr(np, nl)] = !!v; },
  // std/css reactive custom properties: one inline-style property at a time, so a
  // node can carry several without clobbering its whole `style`.
  "dom-set-style-property": (n, np, nl, vp, vl) => { n.style.setProperty(readStr(np, nl), readStr(vp, vl)); },
  "dom-set-text": (n, p, l) => { n.textContent = readStr(p, l); },
  "dom-get-value": (n, dst, cap) => writeStr(dst, cap, (n && n.value) || ""),
  // event accessors (the event externref flows in as the handler's arg).
  "event-target-value": (e, dst, cap) => writeStr(dst, cap, (e && e.target && e.target.value) || ""),
  // `checked` rides the same string-probe shape as `target-value`: "true"/"false",
  // parsed back to a bool in `std/event` (no separate boxed-bool host return path).
  "event-target-checked": (e, dst, cap) => writeStr(dst, cap, (e && e.target && e.target.checked) ? "true" : "false"),
  "event-prevent-default": (e) => { e.preventDefault(); },
  // Register a handler for `name`: the wasm side stowed the closure at `token`; on the
  // event we call the module's exported dispatcher with the token + the event object.
  "dom-add-listener": (n, np, nl, token) =>
    n.addEventListener(readStr(np, nl), (e) => exports.__dom_dispatch(token, e)),
  // Real-timer source for the browser command runtime.
  "dom-set-timeout": (delayMs, token) =>
    setTimeout(() => exports.__browser_resume(token), delayMs),
  // Dev-only key/value store (backed by localStorage): `pluma dev`'s HMR persists
  // the MVU model here so it survives a live-reload. Present unconditionally — a
  // non-HMR build simply never imports these.
  "dom-dev-store-set": (kp, kl, vp, vl) => {
    try { localStorage.setItem(readStr(kp, kl), readStr(vp, vl)); } catch (e) {}
  },
  "dom-dev-store-get": (kp, kl, dst, cap) => {
    let v = "";
    try { v = localStorage.getItem(readStr(kp, kl)) || ""; } catch (e) {}
    return writeStr(dst, cap, v);
  },
  // std/sys/io error/overflow channels, shared by std/web/fetch's marshalled read.
  "io-last-error": (dst, cap) => writeStr(dst, cap, lastError),
  "io-copyout": (dst) => { u8().set(readStash, dst); readStash = new Uint8Array(0); },
  // std/web/fetch — the browser HTTP transport for RPC.
  // The request is "POST\t<url>\t<headers>\t<hex-body>"; the reply pushed back onto the
  // channel `token` is one `next` event of "<status>\t<hex-body>" bytes, then `done`
  // (or `fault` on a network error). An *async* `fetch` (not the old blocking XHR):
  // the wasm caller parks on the channel and the reply wakes it, so concurrent requests
  // no longer freeze the main thread. The single-shot degenerate case of the
  // rpc-stream pull channel — it shares the alloc/event push path and the abort Map.
  "web-fetch-open": (rp, rl, token) => {
    const parts = readStr(rp, rl).split("\t");
    const method = parts[0] || "POST";
    const url = parts[1] || "";
    const headers = {};
    for (const h of (parts[2] || "").split(";")) {
      const i = h.indexOf(":");
      if (i > 0) headers[h.slice(0, i)] = h.slice(i + 1);
    }
    const body = hexDecode(parts[3] || "");
    const ctrl = new AbortController();
    rpcStreams.set(token, ctrl);
    (async () => {
      try {
        const resp = await fetch(url, { method, headers, body, signal: ctrl.signal });
        const raw = new Uint8Array(await resp.arrayBuffer());
        pushStreamEvent(token, 0, enc.encode(resp.status + "\t" + hexEncode(raw))); // next = reply
        pushStreamEvent(token, 1, null);                                            // done
      } catch (e) {
        // A network error faults the stream; an abort (close/cancel) is silent.
        if (!ctrl.signal.aborted) pushStreamEvent(token, 2, null);
      } finally {
        rpcStreams.delete(token);
      }
    })();
  },
  // std/web/stream — the browser RPC *subscription* transport (`stream R` endpoints).
  // Unlike web-fetch (one blocking reply), a subscription is an async `fetch` whose
  // body is read incrementally and parsed as SSE-style events, each pushed into the
  // wasm channel `token`. This integrates with the cooperative scheduler (the puller
  // parks; each event re-readies it) instead of blocking the main thread.
  //
  // Request marshalling matches web-fetch: "POST\t<url>\t<headers>\t<hex-body>".
  // Events (the same framing the native client reads): `event: next\ndata: <hex>\n\n`,
  // `event: done\n\n`, `event: fault\n\n`. Event kinds pushed to wasm: next=0, done=1,
  // fault=2.
  "rpc-stream-open": (rp, rl, token) => {
    const parts = readStr(rp, rl).split("\t");
    const method = parts[0] || "POST";
    const url = parts[1] || "";
    const headers = {};
    for (const h of (parts[2] || "").split(";")) {
      const i = h.indexOf(":");
      if (i > 0) headers[h.slice(0, i)] = h.slice(i + 1);
    }
    const body = hexDecode(parts[3] || "");
    const ctrl = new AbortController();
    rpcStreams.set(token, ctrl);
    (async () => {
      try {
        const resp = await fetch(url, { method, headers, body, signal: ctrl.signal });
        if (!resp.ok || !resp.body) { pushStreamEvent(token, 2, null); return; }
        const reader = resp.body.getReader();
        let buf = "";
        for (;;) {
          const { done, value } = await reader.read();
          if (done) break;
          buf += dec.decode(value, { stream: true });
          let idx;
          while ((idx = buf.indexOf("\n\n")) >= 0) {
            const ev = buf.slice(0, idx);
            buf = buf.slice(idx + 2);
            let kind = "", data = "";
            for (const line of ev.split("\n")) {
              if (line.startsWith("event: ")) kind = line.slice(7);
              else if (line.startsWith("data: ")) data = line.slice(6);
            }
            if (kind === "next") pushStreamEvent(token, 0, hexDecode(data));
            else if (kind === "fault") pushStreamEvent(token, 2, null);
            else if (kind === "done") pushStreamEvent(token, 1, null);
          }
        }
        // Socket closed (no explicit done frame) — a clean end of stream.
        pushStreamEvent(token, 1, null);
      } catch (e) {
        // A network error faults the stream; an abort (close) is silent.
        if (!ctrl.signal.aborted) pushStreamEvent(token, 2, null);
      } finally {
        rpcStreams.delete(token);
      }
    })();
  },
  // Abort a live subscription's reader (the stream's `close`, run on any terminus).
  "rpc-stream-close": (token) => {
    const ctrl = rpcStreams.get(token);
    if (ctrl) { rpcStreams.delete(token); ctrl.abort(); }
  },
};

async function main() {
  const bytes = await (await fetch("app.wasm")).arrayBuffer();
  const { instance } = await WebAssembly.instantiate(bytes, { pluma });
  exports = instance.exports;
  memory = exports.memory;
  // Run the program: builds the initial DOM and registers event listeners.
  exports._entry(null);
}

main().catch((e) => {
  console.error("Pluma app failed to start:", e);
});
"#;
