// The `pluma build --target web` bundle: the WasmGC artifact plus the JS glue
// that runs it in a real browser. `app.wasm` is the compiled module (emitted under
// the `Web` target, so `std.web.dom` lowers to host imports); `loader.js` supplies
// those imports backed by the real DOM and drives the module; `index.html` is a
// minimal shell that loads the loader.
//
// The loader mirrors the sys host's import-object shape (`host/src/v8host.rs`):
// a `{ pluma: { ... } }` object over the module's exported `"memory"`, with each
// `dom-*` import backed by the live `document`. The whole DOM surface is provided
// regardless of which subset a given module imports (extras are ignored), exactly
// as the Rust host registers its full set.

use std::path::Path;

/// Write the three-file browser bundle into `dir`: `app.wasm`, `loader.js`,
/// `index.html`. `dir` is created if missing.
pub(crate) fn write_bundle(dir: &Path, wasm: &[u8]) -> std::io::Result<()> {
	std::fs::create_dir_all(dir)?;
	std::fs::write(dir.join("app.wasm"), wasm)?;
	std::fs::write(dir.join("loader.js"), LOADER_JS)?;
	std::fs::write(dir.join("index.html"), INDEX_HTML)?;
	Ok(())
}

const INDEX_HTML: &str = "<!doctype html>\n\
<html>\n\
<head><meta charset=\"utf-8\"><title>Pluma app</title></head>\n\
<body>\n\
<script type=\"module\" src=\"loader.js\"></script>\n\
</body>\n\
</html>\n";

pub(crate) const LOADER_JS: &str = r#"// Pluma browser loader — instantiates app.wasm and serves its `pluma.*` host
// imports from the real DOM. Generated by `pluma build --target browser`.

const dec = new TextDecoder();
const enc = new TextEncoder();
let memory;   // the module's exported WebAssembly.Memory
let exports;  // the instance's exports (for the event-dispatch callback)
let lastError = "";              // errno-style channel for io-last-error
let readStash = new Uint8Array(0); // overflow buffer drained by io-copyout

// Re-read the backing buffer on every access — a memory.grow swaps it out.
const u8 = () => new Uint8Array(memory.buffer);
const readStr = (ptr, len) => dec.decode(u8().subarray(ptr, ptr + len));
// Write `s`'s UTF-8 into scratch at `dst` (≤ cap bytes) and return its true length.
const writeStr = (dst, cap, s) => {
  const b = enc.encode(s);
  const n = Math.min(b.length, cap < 0 ? 0 : cap);
  u8().set(b.subarray(0, n), dst);
  return b.length;
};
// Deliver raw bytes into the caller's `(dst, cap)` buffer, stashing the overflow for
// `io-copyout` (the marshalling-ABI probe-read shape) — returns the true length.
const deliverBytes = (dst, cap, b) => {
  if (b.length <= (cap < 0 ? 0 : cap)) u8().set(b, dst);
  else readStash = b;
  return b.length;
};
const hexEncode = (b) => {
  let s = "";
  for (let i = 0; i < b.length; i++) s += (b[i] & 0xff).toString(16).padStart(2, "0");
  return s;
};
const hexDecode = (s) => {
  const b = new Uint8Array(s.length >> 1);
  for (let i = 0; i < b.length; i++) b[i] = parseInt(s.substr(i * 2, 2), 16);
  return b;
};

// `__tostring` delegates float formatting here: integers render as `N.0`, the
// rest via the JS default (matches the Rust host's cb_float_to_str).
const floatToStr = (n, ptr, cap) => {
  const s = Number.isFinite(n) && Number.isInteger(n) ? n.toFixed(1) : String(n);
  return writeStr(ptr, cap, s);
};

const pluma = {
  float_to_str: floatToStr,
  // std.web.dom — node handles are opaque JS DOM nodes flowing through wasm $extern boxes.
  "dom-body": () => document.body,
  "dom-create-element": (p, l) => document.createElement(readStr(p, l)),
  "dom-create-text": (p, l) => document.createTextNode(readStr(p, l)),
  "dom-append-child": (parent, child) => { parent.appendChild(child); },
  "dom-insert-before": (parent, node, before) => { parent.insertBefore(node, before); },
  "dom-remove-child": (parent, child) => { parent.removeChild(child); },
  "dom-replace-child": (parent, node, old) => { parent.replaceChild(node, old); },
  "dom-set-attribute": (n, np, nl, vp, vl) => n.setAttribute(readStr(np, nl), readStr(vp, vl)),
  "dom-remove-attribute": (n, p, l) => n.removeAttribute(readStr(p, l)),
  // DOM *property* writes (`node[name] = value`), distinct from attributes: a string
  // property (e.g. `value`) and a bool property (e.g. `checked`/`disabled`). The bool
  // rides as an i32 so `!!flag` is a real boolean (`node.disabled = "false"` is truthy).
  "dom-set-string-property": (n, np, nl, vp, vl) => { n[readStr(np, nl)] = readStr(vp, vl); },
  "dom-set-bool-property": (n, np, nl, v) => { n[readStr(np, nl)] = !!v; },
  "dom-set-text": (n, p, l) => { n.textContent = readStr(p, l); },
  "dom-get-value": (n, dst, cap) => writeStr(dst, cap, (n && n.value) || ""),
  // event accessors (the event externref flows in as the handler's arg).
  "event-target-value": (e, dst, cap) => writeStr(dst, cap, (e && e.target && e.target.value) || ""),
  "event-prevent-default": (e) => { e.preventDefault(); },
  // Register a handler for `name`: the wasm side stowed the closure at `token`; on the
  // event we call the module's exported dispatcher with the token + the event object.
  "dom-add-listener": (n, np, nl, token) =>
    n.addEventListener(readStr(np, nl), (e) => exports.__dom_dispatch(token, e)),
  // Real-timer source for the browser command runtime (Phase 2).
  "dom-set-timeout": (delayMs, token) =>
    setTimeout(() => exports.__browser_resume(token), delayMs),
  // Dev-only key/value store (backed by localStorage): `pluma dev`'s HMR persists
  // the MVU model here so it survives a live-reload. Present unconditionally — a
  // non-HMR build simply never imports these.
  "dom-dev-store-set": (kp, kl, vp, vl) => {
    try { localStorage.setItem(readStr(kp, kl), readStr(vp, vl)); } catch (e) {}
  },
  "dom-dev-store-get": (kp, kl, dst, cap) => {
    let v = "";
    try { v = localStorage.getItem(readStr(kp, kl)) || ""; } catch (e) {}
    return writeStr(dst, cap, v);
  },
  // std.sys.io error/overflow channels, shared by std.web.fetch's marshalled read.
  "io-last-error": (dst, cap) => writeStr(dst, cap, lastError),
  "io-copyout": (dst) => { u8().set(readStash, dst); readStash = new Uint8Array(0); },
  // std.web.fetch — the browser HTTP transport (the web arm of FULLSTACK Layer 2).
  // The request is "POST\t<url>\t<headers>\t<hex-body>"; the reply written back is
  // "<status>\t<hex-body>". Uses a *synchronous* XHR — an async fetch returns a
  // Promise the blocking wasm call can't consume. Binary bodies ride as hex; the
  // `x-user-defined` charset keeps each response byte intact.
  "web-fetch": (rp, rl, dst, cap) => {
    const parts = readStr(rp, rl).split("\t");
    try {
      const xhr = new XMLHttpRequest();
      xhr.open(parts[0] || "POST", parts[1] || "", false);
      xhr.overrideMimeType("text/plain; charset=x-user-defined");
      for (const h of (parts[2] || "").split(";")) {
        const i = h.indexOf(":");
        if (i > 0) xhr.setRequestHeader(h.slice(0, i), h.slice(i + 1));
      }
      xhr.send(hexDecode(parts[3] || ""));
      const raw = xhr.responseText;
      let hex = "";
      for (let i = 0; i < raw.length; i++) hex += (raw.charCodeAt(i) & 0xff).toString(16).padStart(2, "0");
      return deliverBytes(dst, cap, enc.encode(xhr.status + "\t" + hex));
    } catch (e) {
      lastError = String(e);
      return -1;
    }
  },
};

async function main() {
  const bytes = await (await fetch("app.wasm")).arrayBuffer();
  const { instance } = await WebAssembly.instantiate(bytes, { pluma });
  exports = instance.exports;
  memory = exports.memory;
  // Run the program: builds the initial DOM and registers event listeners.
  exports._entry(null);
}

main().catch((e) => {
  console.error("Pluma app failed to start:", e);
});
"#;
