// The `pluma build --target browser` bundle: the WasmGC artifact plus the JS glue
// that runs it in a real browser. `app.wasm` is the compiled module (emitted under
// `Platform::Browser`, so `core.dom` lowers to host imports); `loader.js` supplies
// those imports backed by the real DOM and drives the module; `index.html` is a
// minimal shell that loads the loader.
//
// The loader mirrors the server host's import-object shape (`host/src/v8host.rs`):
// a `{ pluma: { ... } }` object over the module's exported `"memory"`, with each
// `dom-*` import backed by the live `document`. The whole DOM surface is provided
// regardless of which subset a given module imports (extras are ignored), exactly
// as the Rust host registers its full set.

use std::path::Path;

/// Write the three-file browser bundle into `dir`: `app.wasm`, `loader.js`,
/// `index.html`. `dir` is created if missing.
pub(crate) fn write_bundle(dir: &Path, wasm: &[u8]) -> std::io::Result<()> {
	std::fs::create_dir_all(dir)?;
	std::fs::write(dir.join("app.wasm"), wasm)?;
	std::fs::write(dir.join("loader.js"), LOADER_JS)?;
	std::fs::write(dir.join("index.html"), INDEX_HTML)?;
	Ok(())
}

const INDEX_HTML: &str = "<!doctype html>\n\
<html>\n\
<head><meta charset=\"utf-8\"><title>Pluma app</title></head>\n\
<body>\n\
<script type=\"module\" src=\"loader.js\"></script>\n\
</body>\n\
</html>\n";

const LOADER_JS: &str = r#"// Pluma browser loader — instantiates app.wasm and serves its `pluma.*` host
// imports from the real DOM. Generated by `pluma build --target browser`.

const dec = new TextDecoder();
const enc = new TextEncoder();
let memory;   // the module's exported WebAssembly.Memory
let exports;  // the instance's exports (for the event-dispatch callback)

// Re-read the backing buffer on every access — a memory.grow swaps it out.
const u8 = () => new Uint8Array(memory.buffer);
const readStr = (ptr, len) => dec.decode(u8().subarray(ptr, ptr + len));
// Write `s`'s UTF-8 into scratch at `dst` (≤ cap bytes) and return its true length.
const writeStr = (dst, cap, s) => {
  const b = enc.encode(s);
  const n = Math.min(b.length, cap < 0 ? 0 : cap);
  u8().set(b.subarray(0, n), dst);
  return b.length;
};

// `__tostring` delegates float formatting here: integers render as `N.0`, the
// rest via the JS default (matches the Rust host's cb_float_to_str).
const floatToStr = (n, ptr, cap) => {
  const s = Number.isFinite(n) && Number.isInteger(n) ? n.toFixed(1) : String(n);
  return writeStr(ptr, cap, s);
};

const pluma = {
  float_to_str: floatToStr,
  // core.dom — node handles are opaque JS DOM nodes flowing through wasm $extern boxes.
  "dom-body": () => document.body,
  "dom-create-element": (p, l) => document.createElement(readStr(p, l)),
  "dom-create-text": (p, l) => document.createTextNode(readStr(p, l)),
  "dom-append-child": (parent, child) => { parent.appendChild(child); },
  "dom-set-attribute": (n, np, nl, vp, vl) => n.setAttribute(readStr(np, nl), readStr(vp, vl)),
  "dom-set-text": (n, p, l) => { n.textContent = readStr(p, l); },
  "dom-get-value": (n, dst, cap) => writeStr(dst, cap, (n && n.value) || ""),
  // Register a click handler: the wasm side stowed the closure at `token`; on the
  // event we call back into the module's exported dispatcher.
  "dom-add-listener-click": (n, token) =>
    n.addEventListener("click", () => exports.__dom_dispatch(token)),
};

async function main() {
  const bytes = await (await fetch("app.wasm")).arrayBuffer();
  const { instance } = await WebAssembly.instantiate(bytes, { pluma });
  exports = instance.exports;
  memory = exports.memory;
  // Run the program: builds the initial DOM and registers event listeners.
  exports._entry(null);
}

main().catch((e) => {
  console.error("Pluma app failed to start:", e);
});
"#;
